import type { MacroZoneData, RecursiveLandmarkData } from "./worldV2Types"

export const MACRO_ZONES_V2: MacroZoneData[] = [
  {
    id: "basecamp",
    index: 1,
    name: "Basecamp",
    subtitle: "Trailhead & Foundations",
    elevation: "850 m",
    terrainDescription: "Sheltered pine basin, warm timber lodges, stone firepits, gentle foothills",
    curriculumSummary: "Complexity & Problem Solving • Arrays & Strings • Hashing",
    moduleCount: 3,
    state: "completed",
    x: 170,
    y: 720,
    accentColor: "#10B981",
  },
  {
    id: "pattern-meadows",
    index: 2,
    name: "Pattern Meadows",
    subtitle: "Sunlit Terraces & Clearings",
    elevation: "1,240 m",
    terrainDescription: "Open rolling meadows, crystal streams, rustic bridges, wildflowers",
    curriculumSummary: "Two Pointers • Sliding Window • Prefix Sum • Binary Search • Intervals",
    moduleCount: 5,
    state: "completed",
    x: 340,
    y: 610,
    accentColor: "#34D399",
  },
  {
    id: "structure-woods",
    index: 3,
    name: "Structure Woods",
    subtitle: "Timber Canopy & Linear Groves",
    elevation: "1,680 m",
    terrainDescription: "Dense montane forest, stepped timber crossings, mossy granite ravines",
    curriculumSummary: "Linked Lists • Stack & Queue • Heap & Priority Queue • Trie",
    moduleCount: 4,
    state: "completed",
    x: 520,
    y: 530,
    accentColor: "#22C55E",
  },
  {
    id: "recursive-forest",
    index: 4,
    name: "Recursive Forest",
    subtitle: "Ancient Canopy & Stone Portals",
    elevation: "2,150 m",
    terrainDescription: "Ancient old-growth pines, weathered megaliths, branching trails, deep mist",
    curriculumSummary: "Recursion • Backtracking • Trees • Binary Search Trees",
    moduleCount: 4,
    state: "current",
    x: 720,
    y: 430,
    accentColor: "#F59E0B",
  },
  {
    id: "graph-highlands",
    index: 5,
    name: "Graph Highlands",
    subtitle: "Interconnected Ridges & Ravines",
    elevation: "2,780 m",
    terrainDescription: "Vertical rock walls, suspension timber bridges, network of mountain cols",
    curriculumSummary: "Graph Fundamentals • BFS & DFS • Shortest Paths • Union-Find • Topo Sort",
    moduleCount: 5,
    state: "locked",
    x: 930,
    y: 350,
    accentColor: "#64748B",
  },
  {
    id: "optimization-peaks",
    index: 6,
    name: "Optimization Peaks",
    subtitle: "Glacial Arêtes & Couloirs",
    elevation: "3,320 m",
    terrainDescription: "Sheer granite crags, snow couloirs, narrow deliberate climbing ledges",
    curriculumSummary: "1D Dynamic Programming • 2D Dynamic Programming • Greedy Strategies",
    moduleCount: 4,
    state: "locked",
    x: 1120,
    y: 250,
    accentColor: "#64748B",
  },
  {
    id: "interview-summit",
    index: 7,
    name: "Interview Summit",
    subtitle: "Panoramic Crest of Mastery",
    elevation: "3,890 m",
    terrainDescription: "Expansive alpine horn, 360° horizon, grand observation beacon",
    curriculumSummary: "Advanced Algorithms • System Integration • Technical Mock Summit",
    moduleCount: 4,
    state: "locked",
    x: 1290,
    y: 160,
    accentColor: "#64748B",
  },
]

export const RECURSIVE_LANDMARKS_V2: RecursiveLandmarkData[] = [
  {
    id: "recursion",
    name: "Recursion",
    conceptTitle: "The Whispering Megaliths",
    curriculumModuleId: "recursion",
    state: "completed",
    description: "Concentric stone arches echoing along a descending natural amphitheater.",
    environmentalIdentity: "Weathered granite arches covered in moss, stepping downward in self-similar rings.",
    routeStep: 1,
    x: 230,
    y: 690,
    actionLabel: "Review Lessons",
  },
  {
    id: "backtracking",
    name: "Backtracking",
    conceptTitle: "The Forked Crossings",
    curriculumModuleId: "backtracking",
    state: "completed",
    description: "Branching timber catwalks over a mountain stream; trail markers indicate explored forks.",
    environmentalIdentity: "Forked wooden bridges with return paths, carved directional stakes, and lantern guides.",
    routeStep: 2,
    x: 480,
    y: 570,
    actionLabel: "Review Lessons",
  },
  {
    id: "trees",
    name: "Trees",
    conceptTitle: "Ancient Canopy Lodge",
    curriculumModuleId: "trees",
    state: "current",
    isHero: true,
    description: "Two-story cedar timber lodge anchored beneath a monumental thousand-year-old alpine pine.",
    environmentalIdentity: "Hero architectural lodge, stone hearth, warm ember windows, illuminated trail arrival.",
    routeStep: 3,
    x: 760,
    y: 440,
    actionLabel: "Continue Expedition",
  },
  {
    id: "bst",
    name: "Binary Search Trees",
    conceptTitle: "The Ordered Arboretum",
    curriculumModuleId: "binary-search-trees",
    state: "locked",
    description: "Elevated twin-spire timber pavilion with deliberate left and right terraced tiers.",
    environmentalIdentity: "Twin spire pavilions flanking an ancient central cedar, stone steps dividing left/right.",
    routeStep: 4,
    x: 1040,
    y: 350,
    actionLabel: "Locked • Complete Trees",
  },
  {
    id: "highland-pass",
    name: "Highland Pass",
    conceptTitle: "The Cloud Saddle",
    state: "locked",
    isGateway: true,
    description: "High mountain col where the forest yields to sheer granite and drifting alpine mist.",
    environmentalIdentity: "Rock cairns, stone archway threshold, drifting mountain mist revealing distant ridges.",
    routeStep: 5,
    x: 1250,
    y: 260,
    actionLabel: "Zone 5 Gateway • Locked",
  },
]
